version: '3'
services:
  nginx-proxy:
    build: .
    image: rohammosalli/nginx-proxy:v1
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy-net
  dnsmasq:
    build: dnsmasq/.
    image: rohammosalli/dnsmasq:v1
    container_name: dnsmasq-proxy
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq/proxy.conf:/etc/dnsmasq.d/proxy.conf  
    networks:
      - nginx-proxy-net  
networks:
  nginx-proxy-net:
